### ISSUE TITLE
New library: properties to plot as function of iteration?

### ISSUE THREAD

**Issue by artofscience** [artofscience/SAOR#109]
Consider taking a look at the topology optimization examples. As you see this contains a lot of duplicate code related to plotting properties as a function of iteration count.

Imo; preferably the user can choose which properties to plot and how to plot them (e.g. live plotting or at the end).
This would require a library of properties that people commonly plot.

**Comment by aatmdelissen** [comment]
I don't like the idea of a general plot library (other than what `pyplot` already is), because in general users will want very specific plots. For it to work in a good way we need to add a lot of new code which will not be simple to use. Aim should be to keep this kind of 'boilerplate' code to a minimum and just implement some bare essentials for viewing the examples.
The only thing we should focus on is easy accessibility of parameters one might want to plot, such as stepsize, KKT value, objective and constraint values, etc..
